type ActionKey = "jobs" | "services" | "tasks";
type PromptsByLocale = Record<string, Record<string, string[]>>;

const SMART_PROMPTS: Record<ActionKey, PromptsByLocale> = {
  jobs: {
    en: {
      Tech: ["Developer jobs in Casablanca", "Remote IT positions with salary", "Junior software engineer roles"],
      Finance: ["Accounting jobs near me", "Banking positions in Rabat", "Finance internships available"],
      Hospitality: ["Hotel reception jobs hiring now", "Restaurant staff in Marrakech", "Tourism guide positions"],
      Health: ["Nursing positions available", "Pharmacy assistant jobs", "Healthcare jobs in Fès"],
      Legal: ["Law firm assistant positions", "Paralegal openings near me", "Legal secretary jobs"],
      Construction: ["Site manager positions", "Civil engineering roles", "Construction worker hiring now"],
      Education: ["Teaching positions in Casablanca", "Private tutoring opportunities", "School admin roles"],
      CallCenter: ["Call center agent positions", "Remote customer support jobs", "Multilingual call center hiring"],
      Auto: ["Mechanic jobs available", "Auto electrician positions", "Car dealership jobs near me"],
      Cleaning: ["Cleaning staff needed", "Housekeeping positions in hotels", "Office cleaning jobs"],
      Other: ["Part-time jobs near me", "Entry-level positions hiring now", "Jobs posted this week"],
    },
    fr: {
      Tech: ["Développeur à Casablanca", "Postes IT en télétravail avec salaire", "Offres développeur junior"],
      Finance: ["Comptable près de chez moi", "Postes en banque à Rabat", "Stages en finance disponibles"],
      Hospitality: ["Réceptionniste d'hôtel qui recrute", "Personnel de restaurant à Marrakech", "Postes guide touristique"],
      Health: ["Postes infirmier disponibles", "Assistant pharmacie recherché", "Emplois santé à Fès"],
      Legal: ["Assistant cabinet d'avocat", "Postes de parajuriste", "Secrétaire juridique recherché"],
      Construction: ["Chef de chantier recherché", "Postes en génie civil", "Ouvrier BTP qui recrute"],
      Education: ["Postes enseignant à Casablanca", "Cours particuliers opportunités", "Admin scolaire recherché"],
      CallCenter: ["Agent centre d'appel recherché", "Support client en télétravail", "Centre d'appel multilingue"],
      Auto: ["Mécanicien recherché", "Électricien auto disponible", "Postes concessionnaire auto"],
      Cleaning: ["Personnel de nettoyage recherché", "Femme de ménage hôtel", "Nettoyage bureaux offres"],
      Other: ["Emplois temps partiel près de moi", "Postes débutant qui recrutent", "Offres publiées cette semaine"],
    },
    ar: {
      Tech: ["مطور في الدار البيضاء", "وظائف IT عن بعد بالراتب", "وظائف مبتدئ في البرمجة"],
      Finance: ["محاسب قريب مني", "وظائف بنكية في الرباط", "تدريب في المالية متاح"],
      Hospitality: ["استقبال فندق يوظف", "عمال مطعم في مراكش", "مرشد سياحي مطلوب"],
      Health: ["وظائف تمريض متاحة", "مساعد صيدلية مطلوب", "وظائف صحية في فاس"],
      Legal: ["مساعد مكتب محاماة", "وظائف قانونية قريبة مني", "سكرتير قانوني مطلوب"],
      Construction: ["رئيس ورشة مطلوب", "وظائف هندسة مدنية", "عامل بناء يوظف"],
      Education: ["وظائف تدريس في الدار البيضاء", "فرص دروس خصوصية", "إداري مدرسة مطلوب"],
      CallCenter: ["عميل مركز اتصال مطلوب", "دعم عملاء عن بعد", "مركز اتصال متعدد اللغات"],
      Auto: ["ميكانيكي مطلوب", "كهربائي سيارات متاح", "وظائف وكالة سيارات"],
      Cleaning: ["عامل نظافة مطلوب", "تدبير منزلي في فنادق", "تنظيف مكاتب عروض"],
      Other: ["وظائف بدوام جزئي قريبة", "وظائف للمبتدئين", "عروض نشرت هذا الأسبوع"],
    },
  },
  services: {
    en: {
      HomeMaintenance: ["Plumber near me", "Best electrician in Casablanca", "Affordable locksmith available now"],
      ConstructionInstallation: ["Reliable painter in my area", "Tiling service with good reviews", "Renovation contractor near me"],
      HealthWellness: ["Doctor near me with best reviews", "Physical therapist available today", "Affordable clinic in Fès"],
      BeautyPersonalCare: ["Best hairdresser in my city", "Affordable nail salon nearby", "Makeup artist for events"],
      EventsMedia: ["Photographer for wedding", "DJ for birthday party", "Event planner in Casablanca"],
      FoodCatering: ["Catering for 50 people", "Best traiteur in my area", "Private chef for dinner"],
      DigitalCreative: ["Freelance web developer", "Affordable graphic designer", "Social media manager for business"],
      LegalFinance: ["Notary near me", "Accountant for small business", "Insurance advisor available"],
      EducationCoaching: ["Math tutor for my kid", "French teacher available", "Driving school near me"],
      AutomotiveTransport: ["Mechanic near me", "Car towing service", "Auto electrician with best price"],
      Other: ["Best rated services nearby", "Affordable services in my city", "Available providers this week"],
    },
    fr: {
      HomeMaintenance: ["Plombier près de chez moi", "Meilleur électricien à Casablanca", "Serrurier disponible maintenant"],
      ConstructionInstallation: ["Peintre fiable dans ma zone", "Carreleur bien noté", "Entrepreneur rénovation près de moi"],
      HealthWellness: ["Médecin près de moi bien noté", "Kinésithérapeute disponible", "Clinique abordable à Fès"],
      BeautyPersonalCare: ["Meilleur coiffeur dans ma ville", "Salon de manucure abordable", "Maquilleuse pour événements"],
      EventsMedia: ["Photographe pour mariage", "DJ pour anniversaire", "Organisateur événements à Casablanca"],
      FoodCatering: ["Traiteur pour 50 personnes", "Meilleur traiteur près de moi", "Chef privé pour dîner"],
      DigitalCreative: ["Développeur web freelance", "Graphiste abordable", "Community manager pour entreprise"],
      LegalFinance: ["Notaire près de chez moi", "Comptable pour PME", "Conseiller assurance disponible"],
      EducationCoaching: ["Prof de maths pour mon enfant", "Prof de français disponible", "Auto-école près de moi"],
      AutomotiveTransport: ["Mécanicien près de moi", "Service remorquage voiture", "Électricien auto bon prix"],
      Other: ["Meilleurs services près de moi", "Services abordables dans ma ville", "Prestataires disponibles cette semaine"],
    },
    ar: {
      HomeMaintenance: ["سباك قريب مني", "أفضل كهربائي في الدار البيضاء", "نجار متاح الآن"],
      ConstructionInstallation: ["دهان موثوق في منطقتي", "خدمة بلاط بتقييم جيد", "مقاول تجديد قريب مني"],
      HealthWellness: ["طبيب قريب مني بأفضل تقييم", "أخصائي علاج طبيعي متاح", "عيادة بسعر معقول في فاس"],
      BeautyPersonalCare: ["أفضل حلاق في مدينتي", "صالون أظافر قريب", "خبيرة مكياج للمناسبات"],
      EventsMedia: ["مصور لحفل زفاف", "DJ لحفلة عيد ميلاد", "منظم حفلات في الدار البيضاء"],
      FoodCatering: ["طباخ لـ 50 شخص", "أفضل طريتور قريب مني", "شيف خاص لعشاء"],
      DigitalCreative: ["مطور ويب مستقل", "مصمم جرافيك بسعر معقول", "مدير وسائل التواصل"],
      LegalFinance: ["موثق قريب مني", "محاسب لشركة صغيرة", "مستشار تأمين متاح"],
      EducationCoaching: ["أستاذ رياضيات لطفلي", "أستاذ فرنسية متاح", "مدرسة سياقة قريبة مني"],
      AutomotiveTransport: ["ميكانيكي قريب مني", "خدمة سحب سيارة", "كهربائي سيارات بأفضل سعر"],
      Other: ["أفضل الخدمات القريبة", "خدمات بسعر معقول في مدينتي", "مزودين متاحين هذا الأسبوع"],
    },
  },
  tasks: {
    en: {
      MultiSector: ["Quick tasks available today", "Flexible gigs in my area", "Tasks I can start immediately"],
      Health: ["Medical delivery task", "Pharmacy pickup needed", "Health survey task nearby"],
      Cleaning: ["Deep clean my apartment", "Office cleaning this weekend", "Post-renovation cleanup needed"],
      Construction: ["Help with furniture assembly", "Small painting job needed", "Fix a broken door handle"],
      Auto: ["Car wash at my location", "Help move my car", "Quick tire change needed"],
      Tech: ["Set up my Wi-Fi router", "Fix my laptop screen", "Help with phone repair"],
      Finance: ["Data entry task available", "Help with bookkeeping", "Invoice processing needed"],
      Hospitality: ["Waiter for private event", "Help at reception desk", "Bartender for one night"],
      Legal: ["Document scanning and filing", "Translation of legal document", "Notarize papers for me"],
      Education: ["Help my kid with homework", "Prepare study materials", "Record a tutorial video"],
    },
    fr: {
      MultiSector: ["Tâches rapides disponibles aujourd'hui", "Missions flexibles dans ma zone", "Tâches que je peux commencer maintenant"],
      Health: ["Livraison médicale à faire", "Récupération pharmacie nécessaire", "Enquête santé près de moi"],
      Cleaning: ["Grand nettoyage de mon appartement", "Nettoyage bureau ce weekend", "Nettoyage après rénovation"],
      Construction: ["Aide montage de meuble", "Petit travail de peinture", "Réparer une poignée de porte"],
      Auto: ["Lavage voiture à domicile", "Aide pour déplacer ma voiture", "Changement pneu rapide"],
      Tech: ["Installer mon routeur Wi-Fi", "Réparer l'écran de mon PC", "Aide réparation téléphone"],
      Finance: ["Saisie de données disponible", "Aide à la comptabilité", "Traitement de factures"],
      Hospitality: ["Serveur pour événement privé", "Aide à la réception", "Barman pour une soirée"],
      Legal: ["Numérisation et classement", "Traduction document juridique", "Légaliser mes documents"],
      Education: ["Aide aux devoirs pour mon enfant", "Préparer des supports de cours", "Enregistrer une vidéo tutoriel"],
    },
    ar: {
      MultiSector: ["مهام سريعة متاحة اليوم", "عمل مرن في منطقتي", "مهام أبدأها فوراً"],
      Health: ["توصيل طبي مطلوب", "استلام من الصيدلية", "مهمة استبيان صحي قريبة"],
      Cleaning: ["تنظيف عميق لشقتي", "تنظيف مكتب هذا الأسبوع", "تنظيف بعد التجديد"],
      Construction: ["مساعدة في تركيب أثاث", "عمل دهان صغير مطلوب", "إصلاح مقبض باب"],
      Auto: ["غسيل سيارة في موقعي", "مساعدة في نقل سيارتي", "تغيير إطار سريع"],
      Tech: ["تركيب راوتر الواي فاي", "إصلاح شاشة حاسوبي", "مساعدة في إصلاح الهاتف"],
      Finance: ["مهمة إدخال بيانات", "مساعدة في المحاسبة", "معالجة فواتير مطلوبة"],
      Hospitality: ["نادل لحفل خاص", "مساعدة في الاستقبال", "بارمان لليلة واحدة"],
      Legal: ["مسح وأرشفة وثائق", "ترجمة وثيقة قانونية", "توثيق أوراقي"],
      Education: ["مساعدة طفلي في الواجبات", "تحضير مواد دراسية", "تسجيل فيديو تعليمي"],
    },
  },
};

export function getCategoryPrompts(
  action: "jobs" | "services" | "tasks",
  category: string,
  locale: string,
): string[] {
  const lang = locale === "ar" ? "ar" : locale === "fr" ? "fr" : "en";
  return SMART_PROMPTS[action]?.[lang]?.[category] ?? SMART_PROMPTS[action]?.[lang]?.["Other"] ?? [];
}
